# Datos de Credit Default Swaps (CDS) soberanos aproximados en puntos base (bps).
# Un CDS más alto indica mayor riesgo de incumplimiento percibido por el mercado.

data = [
    {"pais": "Argentina",              "region": "Sudamérica",        "iso": "ar", "cds": 1850},
    {"pais": "Venezuela",              "region": "Sudamérica",        "iso": "ve", "cds": 3200},
    {"pais": "Líbano",                 "region": "Medio Oriente",     "iso": "lb", "cds": 2800},
    {"pais": "Rusia",                  "region": "Europa/Asia",       "iso": "ru", "cds": 1200},
    {"pais": "Ucrania",                "region": "Europa del Este",   "iso": "ua", "cds": 950},
    {"pais": "Pakistán",               "region": "Asia",              "iso": "pk", "cds": 780},
    {"pais": "Ghana",                  "region": "África",            "iso": "gh", "cds": 720},
    {"pais": "Ecuador",                "region": "Sudamérica",        "iso": "ec", "cds": 680},
    {"pais": "Egipto",                 "region": "África",            "iso": "eg", "cds": 560},
    {"pais": "Angola",                 "region": "África",            "iso": "ao", "cds": 520},
    {"pais": "Nigeria",                "region": "África",            "iso": "ng", "cds": 480},
    {"pais": "Bolivia",                "region": "Sudamérica",        "iso": "bo", "cds": 420},
    {"pais": "Kenia",                  "region": "África",            "iso": "ke", "cds": 350},
    {"pais": "Turquía",                "region": "Europa/Asia",       "iso": "tr", "cds": 310},
    {"pais": "Colombia",               "region": "Sudamérica",        "iso": "co", "cds": 185},
    {"pais": "Sudáfrica",              "region": "África",            "iso": "za", "cds": 195},
    {"pais": "Brasil",                 "region": "Sudamérica",        "iso": "br", "cds": 165},
    {"pais": "Hungría",                "region": "Europa del Este",   "iso": "hu", "cds": 145},
    {"pais": "Vietnam",                "region": "Asia",              "iso": "vn", "cds": 130},
    {"pais": "Perú",                   "region": "Sudamérica",        "iso": "pe", "cds": 120},
    {"pais": "México",                 "region": "Norteamérica",      "iso": "mx", "cds": 110},
    {"pais": "India",                  "region": "Asia",              "iso": "in", "cds": 110},
    {"pais": "Serbia",                 "region": "Europa",            "iso": "rs", "cds": 110},
    {"pais": "Rumanía",                "region": "Europa del Este",   "iso": "ro", "cds": 135},
    {"pais": "Indonesia",              "region": "Asia",              "iso": "id", "cds": 90},
    {"pais": "Filipinas",              "region": "Asia",              "iso": "ph", "cds": 95},
    {"pais": "Grecia",                 "region": "Europa",            "iso": "gr", "cds": 95},
    {"pais": "Kazajistán",             "region": "Asia Central",      "iso": "kz", "cds": 95},
    {"pais": "Chile",                  "region": "Sudamérica",        "iso": "cl", "cds": 85},
    {"pais": "Israel",                 "region": "Medio Oriente",     "iso": "il", "cds": 85},
    {"pais": "China",                  "region": "Asia",              "iso": "cn", "cds": 65},
    {"pais": "Croacia",                "region": "Europa",            "iso": "hr", "cds": 65},
    {"pais": "Tailandia",              "region": "Asia",              "iso": "th", "cds": 70},
    {"pais": "Italia",                 "region": "Europa",            "iso": "it", "cds": 78},
    {"pais": "Malasia",                "region": "Asia",              "iso": "my", "cds": 55},
    {"pais": "Polonia",                "region": "Europa del Este",   "iso": "pl", "cds": 55},
    {"pais": "Arabia Saudita",         "region": "Medio Oriente",     "iso": "sa", "cds": 55},
    {"pais": "España",                 "region": "Europa",            "iso": "es", "cds": 52},
    {"pais": "Portugal",               "region": "Europa",            "iso": "pt", "cds": 48},
    {"pais": "Emiratos Árabes Unidos", "region": "Medio Oriente",     "iso": "ae", "cds": 45},
    {"pais": "Qatar",                  "region": "Medio Oriente",     "iso": "qa", "cds": 42},
    {"pais": "Estados Unidos",         "region": "Norteamérica",      "iso": "us", "cds": 35},
    {"pais": "Japón",                  "region": "Asia",              "iso": "jp", "cds": 28},
    {"pais": "Corea del Sur",          "region": "Asia",              "iso": "kr", "cds": 30},
    {"pais": "Canadá",                 "region": "Norteamérica",      "iso": "ca", "cds": 25},
    {"pais": "Nueva Zelanda",          "region": "Oceanía",           "iso": "nz", "cds": 20},
    {"pais": "Australia",              "region": "Oceanía",           "iso": "au", "cds": 18},
    {"pais": "Reino Unido",            "region": "Europa",            "iso": "gb", "cds": 18},
    {"pais": "Francia",                "region": "Europa",            "iso": "fr", "cds": 22},
    {"pais": "Alemania",               "region": "Europa",            "iso": "de", "cds": 10},
]
